// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADFiIFL9oylTVVhu0dJ2d9wqC5PndOQ4s',
    appId: '1:354716187513:web:026a61e2667db9eef14da8',
    messagingSenderId: '354716187513',
    projectId: 'ufyp-a18cf',
    authDomain: 'ufyp-a18cf.firebaseapp.com',
    storageBucket: 'ufyp-a18cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHXUgHV9Ub-di3ndewVP3rLAa_-hmbW74',
    appId: '1:354716187513:android:23ab14e6810e5430f14da8',
    messagingSenderId: '354716187513',
    projectId: 'ufyp-a18cf',
    storageBucket: 'ufyp-a18cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKC-0T11FLzUTn_cw-qLLZ0kfdhE5Xglc',
    appId: '1:354716187513:ios:391e59dafd7cb9b7f14da8',
    messagingSenderId: '354716187513',
    projectId: 'ufyp-a18cf',
    storageBucket: 'ufyp-a18cf.appspot.com',
    iosClientId: '354716187513-dqqmtsi6stm1cqhmdr0nnu6omfleobmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKC-0T11FLzUTn_cw-qLLZ0kfdhE5Xglc',
    appId: '1:354716187513:ios:46b810a96c77ced7f14da8',
    messagingSenderId: '354716187513',
    projectId: 'ufyp-a18cf',
    storageBucket: 'ufyp-a18cf.appspot.com',
    iosClientId: '354716187513-9mg5rivumu49s8l3skgt4oetudvrjg9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
